feature/about us page
mmrshk/innovation_forpost pull request #114
Opened 2022-09-10 03:42 UTC by Pakholchuk-Oleh

https://trello.com/c/SuyztAYY/34-create-page-about-us
[ ] add style
[ ] google maps
[ ] view
[ ] icons
[ ] pagination for team

2022-09-10 21:26 UTC, viktoriia-horobets commented on app/assets/stylesheets/about.scss
> +}
add line

2022-09-10 21:26 UTC, viktoriia-horobets commented on app/views/home/about.html.erb
> +</div>
add line

2022-09-10 21:26 UTC, viktoriia-horobets commented on app/views/home/about.html.erb
> +    <h6>Дніпровська міська рада</h6>
please, use i18n

2022-09-10 21:26 UTC, viktoriia-horobets commented on app/views/home/about.html.erb
> +    <h5>Ми працюємо тут</h5>
please, use i18n

2022-09-11 23:26 UTC, Pakholchuk-Oleh commented on app/assets/stylesheets/about.scss
> +}
fixed

2022-09-11 23:26 UTC, Pakholchuk-Oleh commented on app/views/home/about.html.erb
> +</div>
fixed

2022-09-11 23:26 UTC, Pakholchuk-Oleh commented on app/views/home/about.html.erb
> +    <h6>Дніпровська міська рада</h6>
fixed

2022-09-11 23:26 UTC, Pakholchuk-Oleh commented on app/views/home/about.html.erb
> +    <h5>Ми працюємо тут</h5>
fixed

2022-10-10 16:06 UTC, mykhailokonst requested changes

2022-10-10 16:06 UTC, mykhailokonst commented on app/javascript/packs/scripts/team-slider.js
> +const PREV  = document.querySelector('.prev'),
const previousValue  = document.querySelector('.prev');

2022-10-10 16:06 UTC, mykhailokonst commented on app/javascript/packs/scripts/team-slider.js
> +NEXT.addEventListener('click', () => {
nextValue

2022-10-10 16:06 UTC, mykhailokonst commented on app/javascript/packs/scripts/team-slider.js
> +  PREV.classList.add('show');
previousValue

2022-10-10 16:06 UTC, mykhailokonst commented on app/javascript/packs/scripts/team-slider.js
> +  TRACK.style.transform = `translateX(-${index * sliderWidth}px)`;
track

2023-04-02 12:42 UTC, merged