Feature | i18n
mmrshk/innovation_forpost pull request #2
Opened 2022-06-21 20:35 UTC by Pakholchuk-Oleh

2022-06-22 06:10 UTC, mmrshk requested changes
5 thousands files???

firstly, divide, why you did two features in one pr?
secondly, why do you need webpack?

2022-06-22 06:13 UTC, mmrshk commented
And also vendor files must be in .gitignore

2022-06-23 17:35 UTC, Andriy1328 approved these changes
LGTM

2022-06-24 08:00 UTC, mmrshk commented on config/application.rb
> +    config.i18n.default_locale = :en
I think for this site default locale will be `ua`.

2022-06-24 08:02 UTC, mmrshk approved these changes
Fix comments and merge.

2022-06-24 08:04 UTC, mmrshk commented
> Fix comments and merge.

Also please in the future add description to the task. 
1. Link to the task
2. What have you done in this task?

2022-06-24 08:42 UTC, merged