Feature/add sorting and filtering for users
mmrshk/innovation_forpost pull request #68
Opened 2022-08-07 18:06 UTC by viktoriia-horobets

2022-08-27 05:22 UTC, mmrshk commented on app/javascript/packs/scripts/filter.js
> +  console.log(elems)
? :)

2022-08-27 05:22 UTC, mmrshk commented on app/views/admins/_filter.html.erb
> +
Remove extra line

2022-08-27 05:22 UTC, mmrshk commented on config/2_5447532790767687998.enc
> +RXMOfyNTvr0lXrmWALIKQmotbZABNXk/roprKBd2lOWlVdfAT+/Bh95mtRltz5I3TOp2KTDa/zUePXkgrWlLd/neMGnAVsjIN5C9lll5t9/78zX28P5IwfYXErJmxm2wQB6PqtpQPQi3s0BH9xZIRXc/IoThG95o0yf7HdUpD/w4SL3B/z7JtKr4mAUrQ9QAZBUWyP9
What is this?

2022-08-27 05:23 UTC, mmrshk requested changes
Fix comments and remove coverage files.

2022-09-01 11:36 UTC, viktoriia-horobets commented on app/javascript/packs/scripts/filter.js
> +  console.log(elems)
fixed

2022-09-01 11:36 UTC, viktoriia-horobets commented on app/views/admins/_filter.html.erb
> +
done

2022-09-06 10:11 UTC, merged