Update article form with image
mmrshk/innovation_forpost pull request #71
Opened 2022-08-09 12:27 UTC by olcplif

When an article is created or updated, the text is checked for uploaded images. For this, regex checking is used. The IDs of the images are extracted. The ID of the article is written in the records of these images in the DB.

As a result, when the article is deleted, the attached pictures are also deleted.

[https://trello.com/c/1b5q0WU3/79-fix-ckeditor](https://trello.com/c/1b5q0WU3/79-fix-ckeditor)

2022-08-11 08:04 UTC, mmrshk commented on app/services/ck_editor_image_service.rb
> +  def initialize(params)
rename params to file

2022-08-11 08:06 UTC, mmrshk commented on app/services/ck_editor_image_service.rb
> +  def file
do you really need this method?

2022-08-11 08:07 UTC, mmrshk commented on app/services/ck_editor_image_service.rb
> +  def errors
and this?

2022-08-11 08:08 UTC, mmrshk commented on app/services/ck_editor_image_service.rb
> +    @uploaded_image = CkEditorImage.new(file: @file)
empty space after

2022-08-12 11:11 UTC, olcplif commented on app/services/ck_editor_image_service.rb
> +  def initialize(params)
fixed

2022-08-12 11:11 UTC, olcplif commented on app/services/ck_editor_image_service.rb
> +  def file
fixed

2022-08-12 11:11 UTC, olcplif commented on app/services/ck_editor_image_service.rb
> +  def errors
fixed

2022-08-12 11:11 UTC, olcplif commented on app/services/ck_editor_image_service.rb
> +    @uploaded_image = CkEditorImage.new(file: @file)
fixed

2022-08-12 13:42 UTC, mmrshk requested changes
We already have images for tests here -` spec/files`

2022-08-12 16:55 UTC, olcplif commented
> We already have images for tests here -` spec/files`

Yes, but I needed an invalid file to check that it would not be saved to DB

2022-08-15 09:32 UTC, mmrshk requested changes
Why this branch includes changes from other PR's???

2022-08-15 09:42 UTC, merged