Feature/crontask
mmrshk/innovation_forpost pull request #74
Opened 2022-08-12 14:53 UTC by stasfly

Cron tasks for mail sending

2022-08-13 21:27 UTC, olcplif requested changes
please, fix these moments

2022-08-13 21:27 UTC, olcplif commented on app/models/user.rb
> +  scope :only_admins, -> { where(role: %i[super_admin admin]) }
redundant scope

2022-08-13 21:27 UTC, olcplif commented on app/views/test_notifier_mailer.html.egb
> +</body>
empty line

2022-08-13 21:27 UTC, olcplif commented on app/views/test_notifier_mailer.text.egb
> +===============================================
empty line

2022-08-13 21:27 UTC, olcplif commented on config/schedule.yml
> +  queue: default
empty line

2022-08-13 21:27 UTC, olcplif commented on config/sidekiq.yml
> +  - default
empty line

2022-08-13 21:27 UTC, olcplif commented on db/schema.rb
tables for lit disappear

2022-08-13 21:27 UTC, olcplif commented on coverage/.last_run.json
>  {
this folder is in .gitignore

2022-08-15 09:35 UTC, mmrshk requested changes
Why you have changes from another PR's???

2022-08-16 14:47 UTC, closed without merging