Feature/add styles to mailer and add tests
mmrshk/innovation_forpost pull request #93
Opened 2022-08-24 15:57 UTC by bogdanrymar

Add some styles for AnswerMailer, add tests for AnswersController and AnswerMailer

2022-08-31 15:23 UTC, mmrshk commented on app/controllers/admins/answers_controller.rb
> +        @answers = @question.answers.all
`@question.answers`

2022-08-31 15:24 UTC, mmrshk commented on app/views/admins/questions/show.html.erb
> +  <%= form.button :submit%>
`<%= form.button :submit %>`

2022-08-31 15:26 UTC, mmrshk commented on spec/mailers/answer_mailer_spec.rb
> +  end
empty line

2022-08-31 15:26 UTC, mmrshk commented on spec/mailers/answer_mailer_spec.rb
> +  end
set `SMTP_USERNAME` for test env

2022-08-31 15:27 UTC, mmrshk commented on app/views/admins/questions/show.html.erb
> +<%= @question.errors.full_messages %>
remove

2022-08-31 15:28 UTC, mmrshk commented on spec/mailers/answer_mailer_spec.rb
> +    let(:mail) { AnswerMailer.with(answer: answer, question: question, admin: answered_by).question_answered }
`subject { described_class.with(answer: answer, question: question, admin: answered_by).question_answered }`

2022-08-31 15:32 UTC, mmrshk commented on spec/requests/admins/answers_spec.rb
> +
```
let!(:question) { create(:question, :with_answer)
let!(:answer) { question.answers.first )
```

2022-08-31 15:33 UTC, mmrshk commented on spec/requests/admins/answers_spec.rb
> +      let(:invalid_params) { attributes_for(:answer, :invalid_answer) }
empty line

2022-08-31 15:34 UTC, mmrshk commented on spec/requests/admins/answers_spec.rb
> +      let(:invalid_params) { attributes_for(:answer, :invalid_answer) }
remove one of this

2022-08-31 15:34 UTC, mmrshk requested changes
Re-look your PR.

2022-09-05 10:20 UTC, bogdanrymar commented on app/controllers/admins/answers_controller.rb
> +        @answers = @question.answers.all
It gives me error

2022-09-06 08:02 UTC, mmrshk commented on app/controllers/admins/answers_controller.rb
> +        @answers = @question.answers.all
which?

2022-09-06 08:04 UTC, mmrshk commented on spec/mailers/answer_mailer_spec.rb
> +      expect(subject.body.encoded).to match question.title
decide which style you prefer more and use it (with braces or without) 

`expect(subject.body.encoded).to match(question.title)`

I guess we use more braces style. Please, don't mix.

2022-09-06 08:05 UTC, mmrshk commented on spec/requests/admins/answers_spec.rb
> +    end
empty line between contexts!

2022-09-06 08:05 UTC, mmrshk commented on spec/requests/admins/answers_spec.rb
> +
redundant line

2022-09-06 13:31 UTC, merged